[package]
name = "sidescroller_test"
version = "0.1.0"
authors = []

[dependencies]
amethyst = "0.9.0"
tiled = "0.8.0"
log = "0.4"
log4rs = "0.8.0"
rand = "0.5.5"
serde = "1.0.79"
serde_derive = "1.0.79"